model:
  name: "mobilenet_v3_small" # model name on torchvision.models [ "resnet18", "resnet34", "resnet50", "resnet101", "resnet152", "mobilenet_v2", "mobilenet_v3_small", "mobilenet_v3_large", "densenet121", "densenet161", "densenet169", "densenet201" ]
  num_classes: 10